// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs63u4jziXx3QyzG2AsSYJluS1Y4nZlVA',
    appId: '1:1037317279326:web:25981efb7084a854d8aecf',
    messagingSenderId: '1037317279326',
    projectId: 'chat-app-1c3f0',
    authDomain: 'chat-app-1c3f0.firebaseapp.com',
    storageBucket: 'chat-app-1c3f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHqca-aoMKyVcHcq5MSFG1E8i0CkZKVWw',
    appId: '1:1037317279326:android:006e6347f2851abcd8aecf',
    messagingSenderId: '1037317279326',
    projectId: 'chat-app-1c3f0',
    storageBucket: 'chat-app-1c3f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyld-8_dv_iy5uK0cd9irB9SGzYM3zxdc',
    appId: '1:1037317279326:ios:5bb913f888f4a040d8aecf',
    messagingSenderId: '1037317279326',
    projectId: 'chat-app-1c3f0',
    storageBucket: 'chat-app-1c3f0.firebasestorage.app',
    iosBundleId: 'dev.logickoder.flutterChatStarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyld-8_dv_iy5uK0cd9irB9SGzYM3zxdc',
    appId: '1:1037317279326:ios:5bb913f888f4a040d8aecf',
    messagingSenderId: '1037317279326',
    projectId: 'chat-app-1c3f0',
    storageBucket: 'chat-app-1c3f0.firebasestorage.app',
    iosBundleId: 'dev.logickoder.flutterChatStarter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs63u4jziXx3QyzG2AsSYJluS1Y4nZlVA',
    appId: '1:1037317279326:web:b2afc2c160d8039bd8aecf',
    messagingSenderId: '1037317279326',
    projectId: 'chat-app-1c3f0',
    authDomain: 'chat-app-1c3f0.firebaseapp.com',
    storageBucket: 'chat-app-1c3f0.firebasestorage.app',
  );
}
